name: Static Analyzers

on: [ push, pull_request ]

jobs:
  clang_format:
    runs-on: ubuntu-22.04
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Installing clang-format
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 17
          sudo apt install clang-format-17

      - name: Check clang-format
        run: ci/clang-format-check.sh


  cmake_format:
    runs-on: ubuntu-22.04
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install cmake-format
        run: pip install cmake-format  # Simplified to use system Python

      - name: Check cmake-format
        run: ci/cmake-format-check.sh


  code_inspector:
    runs-on: ubuntu-22.04
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run code-inspector
        run: ci/code-inspector-check.sh